services:
  antikom-bot:
    build: .
    container_name: antikom-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATA_DIR: /data
    volumes:
      - ./data:/data
    ports:
      - "3000:3000"
